apiVersion: v1
kind: Namespace
metadata:
  name: pipeline-STAGING_SANDBOX_ID
  labels:
    sandboxId: STAGING_SANDBOX_ID
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: pipeline-chart
  namespace: pipeline-STAGING_SANDBOX_ID
spec:
  interval: 5m0s
  url: https://github.com/biomage-org/pipeline
  ref:
    branch: 2252-gem2s-subset-step
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: pipeline
  namespace: pipeline-STAGING_SANDBOX_ID
spec:
  image: 242905224710.dkr.ecr.eu-west-1.amazonaws.com/pipeline
  interval: 2m0s
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: pipeline
  namespace: pipeline-STAGING_SANDBOX_ID
spec:
  imageRepositoryRef:
    name: pipeline
    namespace: pipeline-STAGING_SANDBOX_ID
  filterTags:
    pattern: ^refs-pull-77-merge-[a-f0-9]+-pipeline-runner-(?P<timestamp>[0-9]+)
    extract: $timestamp
  policy:
    numerical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: pipeline-image-update
  namespace: pipeline-STAGING_SANDBOX_ID
spec:
  interval: 2m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  git:
    commit:
      author:
        name: Flux - Pipeline image update
        email: ci@biomage.net
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pipeline
  namespace: pipeline-STAGING_SANDBOX_ID
  labels:
    sandboxId: STAGING_SANDBOX_ID
spec:
  releaseName: pipeline
  interval: 2m0s
  chart:
    spec:
      chart: chart-infra/
      sourceRef:
        kind: GitRepository
        name: pipeline-chart
        namespace: pipeline-STAGING_SANDBOX_ID
  values:
    replicaCount: 0
    clusterEnv: staging
    sandboxId: STAGING_SANDBOX_ID
    image:
      registry: 242905224710.dkr.ecr.eu-west-1.amazonaws.com
      repository: pipeline
      tag: refs-pull-77-merge-0475d2df6684eb7f497ccff1d4caa80c18f69cb5-pipeline-runner-1670016042 # {"$imagepolicy": "pipeline-STAGING_SANDBOX_ID:pipeline:tag"}
    memoryRequest: 4Gi
    serviceAccount:
      iamRole: pipeline-role-staging
    datadogTags: kube_namespace:pipeline-STAGING_SANDBOX_ID
  valuesFrom:
    - kind: ConfigMap
      valuesKey: account-config.yaml
      name: account-config
      optional: false
