apiVersion: v1
kind: Namespace
metadata:
  name: ui-grasp6-ui149-api87
  labels:
    sandboxId: grasp6-ui149-api87
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: ui-chart
  namespace: ui-grasp6-ui149-api87
spec:
  interval: 5m0s
  url: https://github.com/biomage-org/iac
  ref:
    branch: master
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: ui
  namespace: ui-grasp6-ui149-api87
spec:
  image: 242905224710.dkr.ecr.eu-west-1.amazonaws.com/ui
  interval: 2m0s
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: ui
  namespace: ui-grasp6-ui149-api87
spec:
  imageRepositoryRef:
    name: ui
    namespace: ui-grasp6-ui149-api87
  filterTags:
    pattern: ^refs-pull-149-merge-[a-f0-9]+-(?P<timestamp>[0-9]+)$
    extract: $timestamp
  policy:
    numerical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: ui-image-update
  namespace: ui-grasp6-ui149-api87
spec:
  interval: 2m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  git:
    commit:
      author:
        name: Flux - UI image update
        email: ci@biomage.net
  update:
    strategy: Setters
    path: ./staging
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ui
  namespace: ui-grasp6-ui149-api87
  labels:
    sandboxId: grasp6-ui149-api87
spec:
  releaseName: ui
  interval: 2m0s
  chart:
    spec:
      chart: charts/nodejs
      sourceRef:
        kind: GitRepository
        name: ui-chart
        namespace: ui-grasp6-ui149-api87
      reconcileStrategy: Revision
  values:
    # disable readiness probes as load balancer performs
    # its own health checks/cordoning
    readinessProbe:
      probeType: exec
      command: [echo, '0']
    loadBalancerHealthCheck:
      path: /robots.txt
      periodSeconds: 30
    livenessProbe:
      probeType: tcpSocket
    service:
      additionalHosts: false
    kubernetes:
      env: staging
    biomageCi:
      repo: biomage-org/ui
      sandboxId: grasp6-ui149-api87
    image:
      registry: 242905224710.dkr.ecr.eu-west-1.amazonaws.com
      repository: ui
      tag: refs-pull-149-merge-cfd7b2d7b119ad5afd5540885cd80f94bb87a68f-1673439516 # {"$imagepolicy": "ui-grasp6-ui149-api87:ui:tag"}
    replicaCount: 1
    serviceAccount:
      iamRole: ui-role-staging
  valuesFrom:
  - kind: ConfigMap
    name: account-config
    valuesKey: account-config.yaml
    optional: false
    # filled in by CI. do not modify.
---
apiVersion: v1
kind: Namespace
metadata:
  name: api-grasp6-ui149-api87
  labels:
    sandboxId: grasp6-ui149-api87
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: api-chart
  namespace: api-grasp6-ui149-api87
spec:
  interval: 5m0s
  url: https://github.com/biomage-org/iac
  ref:
    branch: master
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: api
  namespace: api-grasp6-ui149-api87
spec:
  image: 242905224710.dkr.ecr.eu-west-1.amazonaws.com/api
  interval: 2m0s
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: api
  namespace: api-grasp6-ui149-api87
spec:
  imageRepositoryRef:
    name: api
  filterTags:
    pattern: ^refs-pull-87-merge-[a-f0-9]+-(?P<timestamp>[0-9]+)$
    extract: $timestamp
  policy:
    numerical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: api-image-update
  namespace: api-grasp6-ui149-api87
spec:
  interval: 2m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  git:
    commit:
      author:
        name: Flux - API image update
        email: ci@biomage.net
  update:
    strategy: Setters
    path: ./staging
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: api
  namespace: api-grasp6-ui149-api87
  labels:
    sandboxId: grasp6-ui149-api87
spec:
  releaseName: api
  interval: 2m0s
  chart:
    spec:
      chart: charts/nodejs
      sourceRef:
        kind: GitRepository
        name: api-chart
        namespace: api-grasp6-ui149-api87
      reconcileStrategy: Revision
  values:
    service:
      externalPort: 3000
      internalPort: 3000
    readinessProbe:
      path: /v2/health
    livenessProbe:
      probeType: tcpSocket
    resources:
      requests:
        cpu: 100m
    hpa:
      enabled: false
    loadBalancerHealthCheck:
      path: /
    kubernetes:
      env: staging
    biomageCi:
      repo: biomage-org/api
      sandboxId: grasp6-ui149-api87
      rdsSandboxId: default
    image:
      registry: 242905224710.dkr.ecr.eu-west-1.amazonaws.com
      repository: api
      tag: refs-pull-87-merge-1f2b719f42662375da7f69c6650c19b4ea2c8e49-1673462714 # {"$imagepolicy": "api-grasp6-ui149-api87:api:tag"}
    replicaCount: 1
    serviceAccount:
      iamRole: api-role-staging
  valuesFrom:
  - kind: ConfigMap
    name: account-config
    valuesKey: account-config.yaml
    optional: false
# filled in by CI. do not modify.
---
apiVersion: v1
kind: Namespace
metadata:
  name: worker-grasp6-ui149-api87
  labels:
    sandboxId: grasp6-ui149-api87
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: worker-chart
  namespace: worker-grasp6-ui149-api87
spec:
  interval: 5m0s
  url: https://github.com/biomage-org/worker
  ref:
    commit: 4747398318661dbd73e99d3dbf6cf48f941e5cfe
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: worker
  namespace: worker-grasp6-ui149-api87
spec:
  image: 242905224710.dkr.ecr.eu-west-1.amazonaws.com/worker
  interval: 2m0s
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: worker-r
  namespace: worker-grasp6-ui149-api87
spec:
  imageRepositoryRef:
    name: worker
    namespace: worker-grasp6-ui149-api87
  filterTags:
    pattern: ^refs-heads-master-[a-f0-9]+-(?P<timestamp>[0-9]+)-r$
    extract: $timestamp
  policy:
    numerical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: worker-python
  namespace: worker-grasp6-ui149-api87
spec:
  imageRepositoryRef:
    name: worker
  filterTags:
    pattern: ^refs-heads-master-[a-f0-9]+-(?P<timestamp>[0-9]+)-python$
    extract: $timestamp
  policy:
    numerical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: worker-image-update
  namespace: worker-grasp6-ui149-api87
spec:
  interval: 2m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  git:
    commit:
      author:
        name: Flux - Worker image update
        email: ci@biomage.net
  update:
    strategy: Setters
    path: ./staging
  suspend: true
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: worker
  namespace: worker-grasp6-ui149-api87
  labels:
    sandboxId: grasp6-ui149-api87
spec:
  releaseName: worker
  interval: 2m0s
  chart:
    spec:
      chart: chart-infra/
      sourceRef:
        kind: GitRepository
        name: worker-chart
        namespace: worker-grasp6-ui149-api87
      reconcileStrategy: Revision
  values:
    sandboxId: grasp6-ui149-api87
    replicaCount: 0
    r:
      image:
        registry: 242905224710.dkr.ecr.eu-west-1.amazonaws.com
        repository: worker
        tag: refs-heads-master-4747398318661dbd73e99d3dbf6cf48f941e5cfe-1672960115-r # {"$imagepolicy": "worker-grasp6-ui149-api87:worker-r:tag"}
      memoryRequest: 4Gi
    python:
      image:
        registry: 242905224710.dkr.ecr.eu-west-1.amazonaws.com
        repository: worker
        tag: refs-heads-master-4747398318661dbd73e99d3dbf6cf48f941e5cfe-1672960115-python # {"$imagepolicy": "worker-grasp6-ui149-api87:worker-python:tag"}
    kubernetes:
      env: staging
    serviceAccount:
      iamRole: worker-role-staging
    datadogTags: kube_namespace:worker-grasp6-ui149-api87
  valuesFrom:
  - kind: ConfigMap
    valuesKey: account-config.yaml
    name: account-config
    optional: false
---
apiVersion: v1
kind: Namespace
metadata:
  name: pipeline-grasp6-ui149-api87
  labels:
    sandboxId: grasp6-ui149-api87
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: pipeline-chart
  namespace: pipeline-grasp6-ui149-api87
spec:
  interval: 5m0s
  url: https://github.com/biomage-org/pipeline
  ref:
    commit: dd6e2035b91113fde66fbe3bbe2e34840cc2822e
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: pipeline
  namespace: pipeline-grasp6-ui149-api87
spec:
  image: 242905224710.dkr.ecr.eu-west-1.amazonaws.com/pipeline
  interval: 2m0s
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: pipeline
  namespace: pipeline-grasp6-ui149-api87
spec:
  imageRepositoryRef:
    name: pipeline
    namespace: pipeline-grasp6-ui149-api87
  filterTags:
    pattern: ^refs-heads-master-[a-f0-9]+-pipeline-runner-(?P<timestamp>[0-9]+)
    extract: $timestamp
  policy:
    numerical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: pipeline-image-update
  namespace: pipeline-grasp6-ui149-api87
spec:
  interval: 2m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  git:
    commit:
      author:
        name: Flux - Pipeline image update
        email: ci@biomage.net
  update:
    strategy: Setters
    path: ./staging
  suspend: true
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pipeline
  namespace: pipeline-grasp6-ui149-api87
  labels:
    sandboxId: grasp6-ui149-api87
spec:
  releaseName: pipeline
  interval: 2m0s
  chart:
    spec:
      chart: chart-infra/
      sourceRef:
        kind: GitRepository
        name: pipeline-chart
        namespace: pipeline-grasp6-ui149-api87
      reconcileStrategy: Revision
  values:
    replicaCount: 0
    clusterEnv: staging
    sandboxId: grasp6-ui149-api87
    image:
      registry: 242905224710.dkr.ecr.eu-west-1.amazonaws.com
      repository: pipeline
      tag: refs-heads-master-dd6e2035b91113fde66fbe3bbe2e34840cc2822e-pipeline-runner-1673002762 # {"$imagepolicy": "pipeline-grasp6-ui149-api87:pipeline:tag"}
    memoryRequest: 4Gi
    serviceAccount:
      iamRole: pipeline-role-staging
    datadogTags: kube_namespace:pipeline-grasp6-ui149-api87
  valuesFrom:
  - kind: ConfigMap
    valuesKey: account-config.yaml
    name: account-config
    optional: false
