apiVersion: v1
kind: Namespace
metadata:
  name: ui-martinfosco-ui26-api10
  labels:
    sandboxId: martinfosco-ui26-api10
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: ui-chart
  namespace: ui-martinfosco-ui26-api10
spec:
  interval: 5m0s
  url: https://github.com/biomage-org/iac
  ref:
    branch: master
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: ui
  namespace: ui-martinfosco-ui26-api10
spec:
  image: 242905224710.dkr.ecr.eu-west-1.amazonaws.com/ui
  interval: 2m0s
  provider: aws
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: ui
  namespace: ui-martinfosco-ui26-api10
spec:
  imageRepositoryRef:
    name: ui
    namespace: ui-martinfosco-ui26-api10
  filterTags:
    pattern: ^refs-pull-26-merge-[a-f0-9]+-(?P<timestamp>[0-9]+)$
    extract: $timestamp
  policy:
    numerical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: ui-image-update
  namespace: ui-martinfosco-ui26-api10
spec:
  interval: 2m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  git:
    commit:
      author:
        name: Flux - UI image update
        email: ci@biomage.net
  update:
    strategy: Setters
    path: ./staging
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ui
  namespace: ui-martinfosco-ui26-api10
  labels:
    sandboxId: martinfosco-ui26-api10
spec:
  releaseName: ui
  interval: 2m0s
  chart:
    spec:
      chart: charts/nodejs
      sourceRef:
        kind: GitRepository
        name: ui-chart
        namespace: ui-martinfosco-ui26-api10
      reconcileStrategy: Revision
  values:
    # disable readiness probes as load balancer performs
    # its own health checks/cordoning
    readinessProbe:
      probeType: exec
      command: [echo, '0']
    loadBalancerHealthCheck:
      path: /robots.txt
      periodSeconds: 30
    livenessProbe:
      probeType: tcpSocket
    service:
      additionalHosts: false
    kubernetes:
      env: staging
    biomageCi:
      repo: biomage-org/ui
      sandboxId: martinfosco-ui26-api10
    image:
      registry: 242905224710.dkr.ecr.eu-west-1.amazonaws.com
      repository: ui
      tag: refs-pull-26-merge-7c39c1676a7abc4dd62ff5c01964dda483347c16-1696597509 # {"$imagepolicy": "ui-martinfosco-ui26-api10:ui:tag"}
    replicaCount: 1
    serviceAccount:
      iamRole: ui-role-staging
  valuesFrom:
  - kind: ConfigMap
    name: account-config
    valuesKey: account-config.yaml
    optional: false
    # filled in by CI. do not modify.
---
apiVersion: v1
kind: Namespace
metadata:
  name: api-martinfosco-ui26-api10
  labels:
    sandboxId: martinfosco-ui26-api10
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: api-chart
  namespace: api-martinfosco-ui26-api10
spec:
  interval: 5m0s
  url: https://github.com/biomage-org/iac
  ref:
    branch: master
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: api
  namespace: api-martinfosco-ui26-api10
spec:
  image: 242905224710.dkr.ecr.eu-west-1.amazonaws.com/api
  interval: 2m0s
  provider: aws
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: api
  namespace: api-martinfosco-ui26-api10
spec:
  imageRepositoryRef:
    name: api
  filterTags:
    pattern: ^refs-pull-10-merge-[a-f0-9]+-(?P<timestamp>[0-9]+)$
    extract: $timestamp
  policy:
    numerical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: api-image-update
  namespace: api-martinfosco-ui26-api10
spec:
  interval: 2m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  git:
    commit:
      author:
        name: Flux - API image update
        email: ci@biomage.net
  update:
    strategy: Setters
    path: ./staging
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: api
  namespace: api-martinfosco-ui26-api10
  labels:
    sandboxId: martinfosco-ui26-api10
spec:
  releaseName: api
  interval: 2m0s
  chart:
    spec:
      chart: charts/nodejs
      sourceRef:
        kind: GitRepository
        name: api-chart
        namespace: api-martinfosco-ui26-api10
      reconcileStrategy: Revision
  values:
    service:
      externalPort: 3000
      internalPort: 3000
    readinessProbe:
      path: /v2/health
    livenessProbe:
      probeType: tcpSocket
    resources:
      requests:
        cpu: 100m
    hpa:
      enabled: false
    loadBalancerHealthCheck:
      path: /
    kubernetes:
      env: staging
    biomageCi:
      repo: biomage-org/api
      sandboxId: martinfosco-ui26-api10
      rdsSandboxId: default
    image:
      registry: 242905224710.dkr.ecr.eu-west-1.amazonaws.com
      repository: api
      tag: refs-pull-10-merge-aebec9e5862e4e82b7fee5af8dbbbd8e6d18b0d5-1696593375 # {"$imagepolicy": "api-martinfosco-ui26-api10:api:tag"}
    replicaCount: 1
    serviceAccount:
      iamRole: api-role-staging
  valuesFrom:
  - kind: ConfigMap
    name: account-config
    valuesKey: account-config.yaml
    optional: false
# filled in by CI. do not modify.
---
apiVersion: v1
kind: Namespace
metadata:
  name: worker-martinfosco-ui26-api10
  labels:
    sandboxId: martinfosco-ui26-api10
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: worker-chart
  namespace: worker-martinfosco-ui26-api10
spec:
  interval: 5m0s
  url: https://github.com/biomage-org/worker
  ref:
    commit: 11b3d90da687a51a9206aeb4216d12c513196159
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: worker
  namespace: worker-martinfosco-ui26-api10
spec:
  image: 242905224710.dkr.ecr.eu-west-1.amazonaws.com/worker
  interval: 2m0s
  provider: aws
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: worker-r
  namespace: worker-martinfosco-ui26-api10
spec:
  imageRepositoryRef:
    name: worker
    namespace: worker-martinfosco-ui26-api10
  filterTags:
    pattern: ^refs-heads-master-[a-f0-9]+-(?P<timestamp>[0-9]+)-r$
    extract: $timestamp
  policy:
    numerical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: worker-python
  namespace: worker-martinfosco-ui26-api10
spec:
  imageRepositoryRef:
    name: worker
  filterTags:
    pattern: ^refs-heads-master-[a-f0-9]+-(?P<timestamp>[0-9]+)-python$
    extract: $timestamp
  policy:
    numerical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: worker-image-update
  namespace: worker-martinfosco-ui26-api10
spec:
  interval: 2m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  git:
    commit:
      author:
        name: Flux - Worker image update
        email: ci@biomage.net
  update:
    strategy: Setters
    path: ./staging
  suspend: true
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: worker
  namespace: worker-martinfosco-ui26-api10
  labels:
    sandboxId: martinfosco-ui26-api10
spec:
  releaseName: worker
  interval: 2m0s
  chart:
    spec:
      chart: chart-infra/
      sourceRef:
        kind: GitRepository
        name: worker-chart
        namespace: worker-martinfosco-ui26-api10
      reconcileStrategy: Revision
  values:
    sandboxId: martinfosco-ui26-api10
    replicaCount: 0
    r:
      image:
        registry: 242905224710.dkr.ecr.eu-west-1.amazonaws.com
        repository: worker
        tag: refs-heads-master-11b3d90da687a51a9206aeb4216d12c513196159-1695324327-r # {"$imagepolicy": "worker-martinfosco-ui26-api10:worker-r:tag"}
      memoryRequest: 4Gi
    python:
      image:
        registry: 242905224710.dkr.ecr.eu-west-1.amazonaws.com
        repository: worker
        tag: refs-heads-master-11b3d90da687a51a9206aeb4216d12c513196159-1695324327-python # {"$imagepolicy": "worker-martinfosco-ui26-api10:worker-python:tag"}
    kubernetes:
      env: staging
    serviceAccount:
      iamRole: worker-role-staging
    datadogTags: kube_namespace:worker-martinfosco-ui26-api10
  valuesFrom:
  - kind: ConfigMap
    valuesKey: account-config.yaml
    name: account-config
    optional: false
---
apiVersion: v1
kind: Namespace
metadata:
  name: pipeline-martinfosco-ui26-api10
  labels:
    sandboxId: martinfosco-ui26-api10
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: pipeline-chart
  namespace: pipeline-martinfosco-ui26-api10
spec:
  interval: 5m0s
  url: https://github.com/biomage-org/pipeline
  ref:
    commit: 69bb86a33ffabcc8602c1598933f9743f8582213
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: pipeline
  namespace: pipeline-martinfosco-ui26-api10
spec:
  image: 242905224710.dkr.ecr.eu-west-1.amazonaws.com/pipeline
  interval: 2m0s
  provider: aws
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: pipeline
  namespace: pipeline-martinfosco-ui26-api10
spec:
  imageRepositoryRef:
    name: pipeline
    namespace: pipeline-martinfosco-ui26-api10
  filterTags:
    pattern: ^refs-heads-master-[a-f0-9]+-pipeline-runner-(?P<timestamp>[0-9]+)
    extract: $timestamp
  policy:
    numerical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: pipeline-image-update
  namespace: pipeline-martinfosco-ui26-api10
spec:
  interval: 2m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  git:
    commit:
      author:
        name: Flux - Pipeline image update
        email: ci@biomage.net
  update:
    strategy: Setters
    path: ./staging
  suspend: true
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pipeline
  namespace: pipeline-martinfosco-ui26-api10
  labels:
    sandboxId: martinfosco-ui26-api10
spec:
  releaseName: pipeline
  interval: 2m0s
  chart:
    spec:
      chart: chart-infra/
      sourceRef:
        kind: GitRepository
        name: pipeline-chart
        namespace: pipeline-martinfosco-ui26-api10
      reconcileStrategy: Revision
  values:
    replicaCount: 0
    clusterEnv: staging
    sandboxId: martinfosco-ui26-api10
    image:
      registry: 242905224710.dkr.ecr.eu-west-1.amazonaws.com
      repository: pipeline
      tag: refs-heads-master-69bb86a33ffabcc8602c1598933f9743f8582213-pipeline-runner-1696434847 # {"$imagepolicy": "pipeline-martinfosco-ui26-api10:pipeline:tag"}
    memoryRequest: 4Gi
    serviceAccount:
      iamRole: pipeline-role-staging
    datadogTags: kube_namespace:pipeline-martinfosco-ui26-api10
  valuesFrom:
  - kind: ConfigMap
    valuesKey: account-config.yaml
    name: account-config
    optional: false
