apiVersion: v1
kind: Namespace
metadata:
  name: worker-STAGING_SANDBOX_ID
  labels:
    sandboxId: STAGING_SANDBOX_ID
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: worker
  namespace: worker-STAGING_SANDBOX_ID
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/r: glob:refs-pull-32-merge-*-r
    filter.fluxcd.io/python: glob:refs-pull-32-merge-*-python
  labels:
    sandboxId: STAGING_SANDBOX_ID
spec:
  releaseName: worker
  chart:
    git: https://github.com/biomage-org/worker
    path: chart-infra/
    ref: STAGING_CHART_REF
  valuesFrom:
    - configMapKeyRef:
        name: account-config
        namespace: flux
        key: account-config.yaml
  values:
    kubernetes:
      env: staging
    serviceAccount:
      iamRole: worker-role-staging
    sandboxId: STAGING_SANDBOX_ID
    replicaCount: 0
    r:
      image: 242905224710.dkr.ecr.eu-west-1.amazonaws.com/worker:refs-pull-32-merge-12103da7730969606b6d0ce4b95bdb1107b89989-r
      memoryRequest: 4Gi
    python:
      image: 242905224710.dkr.ecr.eu-west-1.amazonaws.com/worker:refs-pull-32-merge-12103da7730969606b6d0ce4b95bdb1107b89989-python
    datadogTags: kube_namespace:worker-STAGING_SANDBOX_ID
